version: "3.9"
services:
  etcd:
    image: bitnami/etcd
    ports:
      - 2379:2379
      - 2380:2380
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379