version: "3.9"
services:
  nacos:
    image: nacos/nacos-server:2.0.0
    container_name: nacos
    restart: unless-stopped
    environment:
    # - PREFER_HOST_MODE=hostname
    - MODE=standalone
    volumes:
    - ./custom.properties:/home/nacos/init.d/custom.properties
    ports:
    - "8848:8848"